typography_spectrum: 0.84868
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7920141245704144
  lightness: 0.14518975489772856
  saturation: 0.946322112577036
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.53844
analytics:
  google: null
  facebook: null
  twitter: null
name: chinery
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Chinery
    id: 66815d66-c0aa-4afd-b914-4d81e0c4f754
    type: content
  - name: Teaching
    id: 8a715819-eb3e-4cac-a902-9a7c28a1e13c
    type: content
  - name: Photography
    id: e2bc47d5-d66f-475b-b3ba-c90e699753ae
    type: content
favicon: null
title: Andrew Chinery
purpose: []
