layout_spectrum: 0.6052340471987971
typography_spectrum: 0.2856877017671261
color:
  brandColors:
    - '#A7304F'
    - '#F46D8D'
    - '#F39EB5'
    - '#081028'
    - '#F0CEB7'
  brandStrength: 0.3638868953257172
  lightness: 1
  saturation: 0.6376044486411432
  rhythmicContrast: 0.8684078953887271
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Andrew Chinery
  email: andrewchinery@gmail.com
  url: 'https://chinery.net'
name: Chinery
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Chinery
    id: 66815d66-c0aa-4afd-b914-4d81e0c4f754
    type: content
  - name: Tutoring
    id: 8a715819-eb3e-4cac-a902-9a7c28a1e13c
    type: content
  - name: Coffee
    id: 9fb38d13-56bc-483c-9aef-20a2cf2b73e7
    type: content
  - name: Coding
    id: 34107b38-3504-4bad-92ea-8d6fa9e90ac5
    type: content
  - name: Photography
    id: e2bc47d5-d66f-475b-b3ba-c90e699753ae
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5dc4b1a7-9cc1-4091-80f4-33a5adf69dd1.png
title: Andrew Chinery
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e53a1ea-e248-40a3-af23-9c8a541743e3.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/3e53a1ea-e248-40a3-af23-9c8a541743e3.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Professional maths and computing tutor, online and around Bletchley. That and
  other hobbies. For all enquiries please email me.
purpose:
  - type: contact
    url: 'mailto:andrewchinery@gmail.com'
    label: Email Chinery
github: true
